# -*- coding: utf-8 -*-
"""Breast Cancer Wisconsin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2B_0Y7o0ysjmND2AqRQ6Gaz8YvowbYW

# Breast Cancer Wisconsin dataset background

**Description:**
This dataset is describing a digitized image of a fine needle aspirate (FNA) of a breast mass. 
I would like to investigate the relationship betweeen the size of breast cell nucleus and having a breast cancer.

**Reason of investigation**
The relationship between the area of breast cell nucleus and having cancer could help the medical to investigate method of verifing the breast cancer.

**G1**: The area of breast cell nucleus of people who has malignant cancer cells

**G2**: The area of breast cell nucleus of people who has benign cancer cells

# Hypothesis

We would be using the area as a response variable. It is a Catergorical variable. As we are measuring and comparing the size larger or smaller.


We are expecting that the malignant cancer cell would have larger size as they contain more DNA then usual cells. Therefore, bigger size.


Data gathered from; https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data?resource=download

If i have unlimited resources and tiime, I would gather as most information as i cann get. For example asking for peremission of acessing data in breast cancer cell in different hospital in different country. In order to have a higher number of data to avoid errors.

# My Dataset
"""

import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/FNAdata.csv")
df

"""G1 (area | diagnosis = M) vs. G2 (area | diagnosis = B)

G1:
"""

## First 5 records of G1 (M)
(df[df['diagnosis'] == 'M']['area_mean']).head(5)

dfM = df[df['diagnosis'] == 'M']
dfMArea = dfM['area_mean']
sumArea = dfMArea.sum()
lenArea = dfMArea.count()
meanArea = sumArea / lenArea
meanArea

"""G2:"""

## First 5 records of G1 (B)
(df[df['diagnosis'] == 'B']['area_mean']).head(5)

dfB = df[df['diagnosis'] == 'B']
dfBArea = dfB['area_mean']
sumArea = dfBArea.sum()
lenArea = dfBArea.count()
meanArea = sumArea / lenArea
meanArea

"""# Conclusion
The malignant cancer cell has an area mean of 978. The benign cancer cell has an area mean of 463. Therefore, we can see a very apperant different between the malignant cancer cell and benign cancer cell.
"""